[phases.setup]
nixPkgs = ["...", "python311", "tesseract"]
nixLibs = ["gcc-unwrapped", "zlib"]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile",
  "python3 -m venv /app/.pythonlibs && /app/.pythonlibs/bin/pip install numpy opencv-python-headless pillow pytesseract"
]